# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Z7ik1itkBFJj9n8mkFFwATiL9An-LQl
"""

import pandas as pd

df=pd.read_csv("Heart.csv")

print(df.to_string())

df.isnull()

df.info()

df.head(5)

df.tail(5)

df1=df.isnull().sum()

print(df1)

df2=df.isnull().sum().sum()

print(df2)

df.tail(10)

df3=df.fillna(value=0)

print(df3)

df3=df.fillna(value=5)

print(df3)

df4=df.fillna(method='pad')

print(df3)

print(df4)

df5=df.fillna(method='bfill')

print(df5)

df6=df.fillna(value=df['Ca'].mean())

print(df6)

df7=df.fillna(value=df['Ca'].min())

print(df7)

df8=df.fillna(value=df['Ca'].max())

print(df8)

df.dtypes

df9=df.fillna(value=df['Age'].min())

print(df9)

print(df['Age'].min())

df10=df.shape

print(df10)

zeros_count = (df == 0).sum()

print(zeros_count)

import matplotlib.pyplot as plt

selected_column = 'Age'
plt.hist(df[selected_column], bins=20, color='skyblue', edgecolor='black')
plt.title(f'Histogram for {selected_column}')
plt.xlabel(selected_column)
plt.ylabel('Frequency')
plt.show()

selected_columns = ['Age', 'Chol']
df[selected_columns].hist(bins=20, figsize=(10, 5))
plt.suptitle('Histogram for Selected Columns')
plt.show()